# fly.toml app configuration file generated for mailgun-contact-form on 2023-08-27T19:44:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mailgun-contact-form"
primary_region = "ord"

[build]

[env]
  RUST_LOG = "mailgun_contact_form=info"

[http_service]
  internal_port = 8088
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
